### ISSUE TITLE
More boolean constants

### ISSUE THREAD

**Issue by DanBarrans** [pcherna/vscode-scalascript#1]
I recall ScalaScript has (had?) more boolean constants, (T|F|0|1) and maybe (Y|Yes|N|No) too. I don’t recall if they are supported in all of expressions, constant parameters, and embedded text formatting codes, but I know they’re in there somewhere. I can’t verify this now as I don’t have access to a player to try it out.

**Comment by pcherna** [comment]
Only On/Off/True/False are supported in ScalaScript. I verified.

Since the extension does syntax coloring, but not syntax checking, should any additional constants be added (or should there be obscure existing ones overlooked), they won't be colored but otherwise would not cause any issues.

If someone presents a valid ScalaScript example that works incorrectly, then I could look at it. Absent that, there is nothing to fix.

**Comment by DanBarrans** [comment]
If interested, and if you have a copy of Designer, you could look at the embedded text codes help in Designer's help menu to see if they're supported there. Just passing along some information no longer useful to me. In any case, it didn't look like your extension does any colorization of embedded codes anyway unless I missed it. Not at all critical of course.
